### ISSUE TITLE
Add More Needed Mods

### ISSUE THREAD

**Issue by Sussy-OS** [Asguho/AsguhoClient#4]
Hello. Please add Cloth Config API to this mod, so that some mod menu configs work.

**Comment by Sussy-OS** [comment]
Could you also add g4mespeed?

**Comment by Asguho** [comment]
> ###
> **[Sussy-OS](/Sussy-OS) ** commented [Apr 24, 2023](#issue-1681396723) •

which mods needs this dependency?

**Comment by Asguho** [comment]
> Could you also add g4mespeed and essential, and maybe zoomify too?

- Zooming should already work just by pressing "c". 
- I will look into g4mespeed. The tick manipulation is already implemented by carpet, but the the improved reliability sounds interesting.
- Essential won't be added to the core modpack, but you are always able to add your own mods on top.

**Comment by Sussy-OS** [comment]
> > Hello. Please add Cloth Config API to this mod, so that some mod menu configs work.
> 
> Hello Sussy. Which mods needs Cloth Config API as a dependency?

I am not sure, all the console said was that the mod was required for some configurations to work properly.

**Comment by Sussy-OS** [comment]
> > Could you also add g4mespeed and essential, and maybe zoomify too?
> 
> * Zooming should already work just by pressing "c".
> * I will look into g4mespeed. The tick manipulation is already implemented by carpet, but the the improved reliability sounds interesting.
> * Essential won't be added to the core modpack, but you are always able to add your own mods on top.

Zoomify adds adjustable zoom just by scrolling your mouse wheel though, so I thought that may be useful or replace the current zoom mod entirely.

Carpet's tick manipulation is good, but G4mespeed's is amazing. I would take a look at it if I were you.

Okay, no problem.
